export const SET_TOP_STORIES = "SET_STORIES";
export const TOGGLE_FETCHING_STATE = "TOGGLE_FETCHING_STATE";

export const SET_CATEGORYWISE_STORIES = "SET_CATEGORYWISE_STORIES";
export const TOGGLE_CATEGORY_FETCHING_STATE = "TOGGLE_CATEGORY_FETCHING_STATE";

export const SET_WORLD_STORIES = "SET_WORLD_STORIES";
