export const SET_TOP_STORIES = "SET_STORIES";
export const TOGGLE_FETCHING_STATE = "TOGGLE_FETCHING_STATE";

export const SET_SOURCE_STORIES = "SET_SOURCE_STORIES";
export const TOGGLE_SOURCE_FETCHING_STATE = "TOGGLE_SOURCE_FETCHING_STATE";

export const SET_CATEGORYWISE_STORIES = "SET_CATEGORYWISE_STORIES";
export const TOGGLE_CATEGORY_FETCHING_STATE = "TOGGLE_CATEGORY_FETCHING_STATE";

export const SET_WORLD_STORIES = "SET_WORLD_STORIES";
export const TOGGLE_WORLD_STORIES_STATE = "TOGGLE_WORLD_STORIES_STATE";

export const SET_SEARCH_STORIES = "SET_SEARCH_STORIES";
export const TOGGLE_SEARCH_FETCHING_STATE = "TOGGLE_SEARCH_FETCHING_STATE";
